spring:
  data:
    mongodb:
      host: localhost
      auto-index-creation: true
  mongodb:
    embedded:
      version: 5.0.5
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      write-dates-as-timestamps: false
  sendgrid:
    api-key: your-api-key
    template-id: your-template-id

debug: false

cors:
  enabled: true
  allowed-origin: http://localhost:3000

jwt:
  secret: 'example'

BASE-URL: your-base-url



