spring:
  data:
    mongodb:
      host: localhost
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      write-dates-as-timestamps: false
  sendgrid:
    api-key: your-api-key
    template-id: your-template-id
    sender-email: sender-email-id
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
          github:
            client-id: your-github-client-id
            client-secret: your-github-client-secret
            scope: user:email

debug: false

cors:
  enabled: true
  allowed-origin: http://localhost:3000

jwt:
  secret: 'example'

base-url: your-base-url
frontend-domain: localhost
