spring:
  data:
    mongodb:
      host: localhost
      auto-index-creation: true
  mongodb:
    embedded:
      version: 5.0.5
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      write-dates-as-timestamps: false

debug: false

cors:
  enabled: true
  allowed-origins:
    - http://localhost:3000

jwt:
  secret: 'example'
