name: Docs

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Copy config
        run: cp ./server/src/main/resources/application.example.yml ./server/src/main/resources/application.yml
      - name: Run test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Move directory
        run: |
          mv server/build/coverage docs/coverage
          mv server/build/reports/tests/test docs/test
      - name: Push coverage report
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git branch -D gh-pages || echo "Branch does not exist"
          git checkout --orphan gh-pages
          git rm --cached $(git ls-files)
          git add docs/*
          git commit -m "Update docs"
          git push -f origin gh-pages
